import { StyleSheet } from 'react-native';

export const styleadmin = StyleSheet.create({
  containerGlobal: {
    flex: 1,
    backgroundColor: '#f9f9f9',
    padding: 20,
    justifyContent: 'flex-start',
  },
  headerLogo: {
    width: 250,
    height: 80,
    alignSelf: 'center',
    resizeMode: 'contain',
    marginBottom: 20,
  },
  headingadmin: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1a1a1a',
    textAlign: 'center',
    marginVertical: 20,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 12,
    marginRight: 12,
    borderColor: '#e0e0e0',
    borderWidth: 1,
    fontSize: 16,
    color: '#333',
  },
  buttonGroup: {
    flexDirection: 'row',
    gap: 10,
  },
  userListItem: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 18,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    flexDirection: 'row',
    alignItems: 'center',
    borderLeftWidth: 4,
    borderLeftColor: '#5271ff',
  },
  userImage: {
    width: 85,
    height: 85,
    borderRadius: 42.5,
    marginRight: 15,
    borderWidth: 2,
    borderColor: '#5271ff',
  },
  userInfoContainer: {
    flex: 1,
    paddingRight: 10,
  },
  userName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    marginBottom: 6,
  },
  userDepartment: {
    fontSize: 14,
    color: '#777',
    marginBottom: 5,
  },
  userPosition: {
    fontSize: 14,
    color: '#777',
    marginBottom: 5,
  },
  userInfoText: {
    fontSize: 14,
    color: '#555',
    marginBottom: 3,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  separator: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginVertical: 10,
  },
  noUsersText: {
    textAlign: 'center',
    color: '#888',
    fontSize: 18,
    marginTop: 30,
    fontWeight: '500',
  },
  loaderContainer: {
    marginTop: 30,
    alignItems: 'center',
  },
  sortButton: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    backgroundColor: '#007AFF',
    borderRadius: 8,
    alignItems: 'center',
  },
  sortButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  pageNumber: {
    fontSize: 16,
    fontWeight: '600',
    marginHorizontal: 15,
  },
  paginationButton: {
    backgroundColor: '#007AFF',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  paginationText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  historyButton: {
    backgroundColor: '#5271ff',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 15,
  },
  historyButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    alignItems: 'center',
    marginBottom: 20,
  },
  modeSwitchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginVertical: 15,
  },
  modeSwitchText: {
    fontSize: 15,
    marginRight: 12,
    color: '#333',
  },
  buttonIcon: {
    width: 24,
    height: 24,
    tintColor: '#fff',
    marginRight: 8,
  },
  userStatus: {
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 6,
  },
  activeStatus: {
    color: 'green',
  },
  inactiveStatus: {
    color: 'red',
  },
  blockedStatus: {
    color: 'black', 
  },
});
